///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case5 recording.
    /// </summary>
    [TestModule("2e7c2dfb-d0c8-45c5-b0d7-e465cedcbe04", ModuleType.Recording, 1)]
    public partial class Case5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Case5 instance = new Case5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case5()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case5 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.StickyHeader' at 289;42.", repo.ApplicationUnderTest.StickyHeaderInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.StickyHeader.Click("289;42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Trendyol' at 124;21.", repo.ApplicationUnderTest.TrendyolInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Trendyol.Click("124;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 497;144.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Self.Click("497;144");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 100;99.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("100;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1615;368.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Self.Click("1615;368");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn2' at 28;21.", repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn2Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn2.Click("28;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1' at 31;23.", repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1.MoveTo("31;23");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(7));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1' at 31;23.", repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.PrdctCntnrWrppr1.FvrtBtn1.MoveTo("31;23");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 1655;59.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("1655;59");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Favorilerim' at 25;7.", repo.ApplicationUnderTest.FavorilerimInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Favorilerim.Click("25;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 616;35.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("616;35");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FavoritesWrapper' at 1663;453.", repo.ApplicationUnderTest.FavoritesWrapperInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.FavoritesWrapper.Click("1663;453");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
