///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case8 recording.
    /// </summary>
    [TestModule("a085c5c2-03c0-4c98-966b-a48df8f74f2e", ModuleType.Recording, 1)]
    public partial class Case8 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Case8 instance = new Case8();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case8()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case8 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekme' at 9;21.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekmeInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekme.Click("9;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekme1' at 64;53.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekme1Info, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.YeniSekme1.Click("64;53");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'microsoft topluluk{Return}' with focus on 'YeniSekme'.", repo.YeniSekme.SelfInfo, new RecordItemIndex(2));
            repo.YeniSekme.Self.EnsureVisible();
            Keyboard.Press("microsoft topluluk{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.None' at 28;231.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.NoneInfo, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.None.Click("28;231");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftToplulukGoogledaAra.MicrosoftCommunity' at 77;22.", repo.MicrosoftToplulukGoogledaAra.MicrosoftCommunityInfo, new RecordItemIndex(4));
            repo.MicrosoftToplulukGoogledaAra.MicrosoftCommunity.Click("77;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftCommunity.CategoryListGrid' at 1569;92.", repo.MicrosoftCommunity.CategoryListGridInfo, new RecordItemIndex(5));
            repo.MicrosoftCommunity.CategoryListGrid.Click("1569;92");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftCommunity.LinkHomeCategoryOutlookComImg' at 34;52.", repo.MicrosoftCommunity.LinkHomeCategoryOutlookComImgInfo, new RecordItemIndex(6));
            repo.MicrosoftCommunity.LinkHomeCategoryOutlookComImg.Click("34;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftCommunity.HesabımKendiliğindenOutlookaGecmişB' at 110;15.", repo.MicrosoftCommunity.HesabımKendiliğindenOutlookaGecmişBInfo, new RecordItemIndex(7));
            repo.MicrosoftCommunity.HesabımKendiliğindenOutlookaGecmişB.Click("110;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MicrosoftCommunity.ThreadQuestionTitleStatusIcons'.", repo.MicrosoftCommunity.ThreadQuestionTitleStatusIconsInfo, new RecordItemIndex(8));
            Validate.Exists(repo.MicrosoftCommunity.ThreadQuestionTitleStatusIconsInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftCommunity.ThreadMessageContentReplyAndMessage' at 998;37.", repo.MicrosoftCommunity.ThreadMessageContentReplyAndMessageInfo, new RecordItemIndex(9));
            repo.MicrosoftCommunity.ThreadMessageContentReplyAndMessage.Click("998;37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MicrosoftCommunity.MerhabaMustafa51533AdımJenAynıZ'.", repo.MicrosoftCommunity.MerhabaMustafa51533AdımJenAynıZInfo, new RecordItemIndex(10));
            Validate.Exists(repo.MicrosoftCommunity.MerhabaMustafa51533AdımJenAynıZInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
