///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case6 recording.
    /// </summary>
    [TestModule("2ba3a75b-b60b-4850-9959-03c71465da34", ModuleType.Recording, 1)]
    public partial class Case6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Case6 instance = new Case6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Trendyol' at 54;28.", repo.ApplicationUnderTest.TrendyolInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Trendyol.Click("54;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1605;50.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("1605;50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Sepetim' at 25;7.", repo.ApplicationUnderTest.SepetimInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Sepetim.Click("25;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 1639;24.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("1639;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 52;8.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("52;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1188;733.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Self.Click("1188;733");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PrdctCntnrWrppr' at 411;12.", repo.ApplicationUnderTest.PrdctCntnrWrpprInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.PrdctCntnrWrppr.Click("411;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
