///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case1 recording.
    /// </summary>
    [TestModule("5314c2ce-b1f8-4eaa-a101-8ad29c9a75d8", ModuleType.Recording, 1)]
    public partial class Case1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Case1 instance = new Case1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Trendyol' at 64;30.", repo.ApplicationUnderTest.TrendyolInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Trendyol.Click("64;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1283;52.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("1283;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl' at 28;14.", repo.ApplicationUnderTest.LoginRegister.UEyeOlInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl.Click("28;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecond' at 144;22.", repo.ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecondInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecond.Click("144;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 184;19.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RegisterEmail.Click("184;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPasswordInput' at 148;24.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RegisterPasswordInput.Click("148;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.LrContainer' at 407;459.", repo.ApplicationUnderTest.LoginRegister.LrContainerInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.LoginRegister.LrContainer.Click("407;459");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
