///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Case2 recording.
    /// </summary>
    [TestModule("83cf9a06-c36b-45e4-aa22-1f364df6fb0c", ModuleType.Recording, 1)]
    public partial class Case2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Case2 instance = new Case2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Case2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Case2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecond' at 143;26.", repo.ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecondInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.LoginRegister.ButtonQButtonQButtonMediumQSecond.Click("143;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 181;11.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RegisterEmail.Click("181;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'eminetsiligkir{RShiftKey down}@{RShiftKey up}hotmail.com' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("eminetsiligkir{RShiftKey down}@{RShiftKey up}hotmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPasswordInput' at 66;17.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RegisterPasswordInput.Click("66;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrima' at 226;23.", repo.ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrimaInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.LoginRegister.QButtonQButtonMediumQFluidQPrima.Click("226;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.LrContainer' at 403;304.", repo.ApplicationUnderTest.LoginRegister.LrContainerInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.LoginRegister.LrContainer.Click("403;304");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
