///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TaskTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a9c22518-0b68-4933-b1b0-cfd5f4a02574")]
    public partial class TaskTestRepository : RepoGenBaseFolder
    {
        static TaskTestRepository instance = new TaskTestRepository();
        TaskTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TaskTestRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        TaskTestRepositoryFolders.YeniSekmeAppFolder _yenisekme;
        TaskTestRepositoryFolders.MicrosoftToplulukGoogledaAraAppFolder _microsofttoplulukgoogledaara;
        TaskTestRepositoryFolders.MicrosoftCommunityAppFolder _microsoftcommunity;

        /// <summary>
        /// Gets the singleton class instance representing the TaskTestRepository element repository.
        /// </summary>
        [RepositoryFolder("a9c22518-0b68-4933-b1b0-cfd5f4a02574")]
        public static TaskTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TaskTestRepository() 
            : base("TaskTestRepository", "/", null, 0, false, "a9c22518-0b68-4933-b1b0-cfd5f4a02574", ".\\RepositoryImages\\TaskTestRepositorya9c22518.rximgres")
        {
            _applicationundertest = new TaskTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _entrendueruenlertuerkiyeninonlineal = new TaskTestRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _yenisekme = new TaskTestRepositoryFolders.YeniSekmeAppFolder(this);
            _microsofttoplulukgoogledaara = new TaskTestRepositoryFolders.MicrosoftToplulukGoogledaAraAppFolder(this);
            _microsoftcommunity = new TaskTestRepositoryFolders.MicrosoftCommunityAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a9c22518-0b68-4933-b1b0-cfd5f4a02574")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cff41e5e-1b2e-44e3-98d6-b4bb76bda1da")]
        public virtual TaskTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("0d125380-9fc3-44b8-80b0-1937ada36724")]
        public virtual TaskTestRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The YeniSekme folder.
        /// </summary>
        [RepositoryFolder("96ba9b8d-3ed2-4e78-957d-6c42a797a14f")]
        public virtual TaskTestRepositoryFolders.YeniSekmeAppFolder YeniSekme
        {
            get { return _yenisekme; }
        }

        /// <summary>
        /// The MicrosoftToplulukGoogledaAra folder.
        /// </summary>
        [RepositoryFolder("abde5879-1b94-43b8-920e-2a2e2d28a9e0")]
        public virtual TaskTestRepositoryFolders.MicrosoftToplulukGoogledaAraAppFolder MicrosoftToplulukGoogledaAra
        {
            get { return _microsofttoplulukgoogledaara; }
        }

        /// <summary>
        /// The MicrosoftCommunity folder.
        /// </summary>
        [RepositoryFolder("7172a158-0707-4484-be5b-48ecd73b2ee3")]
        public virtual TaskTestRepositoryFolders.MicrosoftCommunityAppFolder MicrosoftCommunity
        {
            get { return _microsoftcommunity; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TaskTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cff41e5e-1b2e-44e3-98d6-b4bb76bda1da")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TaskTestRepositoryFolders.LoginRegisterFolder _loginregister;
            TaskTestRepositoryFolders.PrdctCntnrWrppr1Folder _prdctcntnrwrppr1;
            RepoItemInfo _trendyolInfo;
            RepoItemInfo _registeremailInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _errorboxwrapperInfo;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _gotobasketbuttonvisibleInfo;
            RepoItemInfo _sepetim28ueruenInfo;
            RepoItemInfo _httpscdndsmcdncommnresize200200Info;
            RepoItemInfo _prdctcntnrwrpprInfo;
            RepoItemInfo _addtobasketbuttonInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _stickyheaderInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetim31ueruenInfo;
            RepoItemInfo _pbheaderwrapperInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _favoriteswrapperInfo;
            RepoItemInfo _containerInfo;
            RepoItemInfo _somepathtagInfo;
            RepoItemInfo _someatagInfo;
            RepoItemInfo _kaydetvedevametInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "cff41e5e-1b2e-44e3-98d6-b4bb76bda1da", "")
            {
                _loginregister = new TaskTestRepositoryFolders.LoginRegisterFolder(this);
                _prdctcntnrwrppr1 = new TaskTestRepositoryFolders.PrdctCntnrWrppr1Folder(this);
                _trendyolInfo = new RepoItemInfo(this, "Trendyol", ".//a[#'logo']/img[@alt='Trendyol']", ".//a[#'logo']/img[@alt='Trendyol']", 30000, null, "9e435642-11a5-4827-b48a-354c599cf895");
                _registeremailInfo = new RepoItemInfo(this, "RegisterEmail", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "2e7b06a3-2314-4385-97d8-27231944fda1");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "aec17f8e-c5c5-4cc2-83af-f3fcf4d27463");
                _errorboxwrapperInfo = new RepoItemInfo(this, "ErrorBoxWrapper", ".//div[#'error-box-wrapper']", ".//div[#'error-box-wrapper']", 30000, null, "7bbc9bb5-9329-4750-bd29-0609e7f4543b");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "83cbc7dd-b14e-4e31-883a-ac4c791bba2f");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "eeb68997-f978-449d-ae10-779ff99b63c8");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[2]/button/div[@innertext='Sepete Ekle']", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[2]/div[1]/div[2]/button/div[@innertext='Sepete Ekle']", 30000, null, "b3991852-ece6-43a6-b103-ca27254232bd");
                _gotobasketbuttonvisibleInfo = new RepoItemInfo(this, "GoToBasketButtonVisible", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[3]/div[1]/div[1]", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[3]/div[1]/div[1]", 30000, null, "13656bd6-316a-43c4-845c-fcb07027980b");
                _sepetim28ueruenInfo = new RepoItemInfo(this, "Sepetim28UEruen", ".//div[#'pb-container']//div[@innertext='Sepetim (28 Ürün)']", ".//div[#'pb-container']//div[@innertext='Sepetim (28 Ürün)']", 30000, null, "1352cbf0-08fc-4a45-b403-701243333497");
                _httpscdndsmcdncommnresize200200Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize200200", "descendant-or-self::*/div[#'browsing-gw-homepage']/div/div[1]/div/div[2]/a[2]/img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2022/3/7/Coksatanlar1_202203072239.png']", "", 30000, null, "824c4764-73f1-4f0f-bcaf-a1aa5628112c");
                _prdctcntnrwrpprInfo = new RepoItemInfo(this, "PrdctCntnrWrppr", "descendant-or-self::*/*/div/div[1]/?/?/?", "", 30000, null, "2a233f7a-e2cd-4bdb-8a40-9fe00005b988");
                _addtobasketbuttonInfo = new RepoItemInfo(this, "AddToBasketButton", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div/div[1]/div[1]/div[2]/button", ".//div[#'search-app']//button", 30000, null, "0ae305a8-494d-411b-bee9-1dad66dde891");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//div[#'container']/div[3]", ".//div[#'container']/div[3]", 30000, null, "53ee6a1a-10b7-4e47-8c5a-a0a6eb8eba61");
                _stickyheaderInfo = new RepoItemInfo(this, "StickyHeader", ".//div[#'sticky-header']", ".//div[#'sticky-header']", 30000, null, "e5736982-173b-4782-8011-c3ce8ed58609");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "a61cca7c-23bd-42f0-b01b-f44678dfa60a");
                _sepetim31ueruenInfo = new RepoItemInfo(this, "Sepetim31UEruen", ".//div[#'pb-container']//div[@innertext='Sepetim (31 Ürün)']", ".//div[#'pb-container']//div[@innertext='Sepetim (31 Ürün)']", 30000, null, "fb1b7390-854a-444f-8d87-a89a5d7c51b2");
                _pbheaderwrapperInfo = new RepoItemInfo(this, "PbHeaderWrapper", ".//div[#'pb-container']/div/div[1]", ".//div[#'pb-container']/div/div[1]", 30000, null, "012d566b-bde8-4768-aa01-38e429ce3d9b");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "47a57b60-2898-4754-b8a2-6942e58f7521");
                _favoriteswrapperInfo = new RepoItemInfo(this, "FavoritesWrapper", ".//div[#'account-gw-favorites']/div", ".//div[#'account-gw-favorites']/div", 30000, null, "8b0f61ab-1017-4dfa-b84f-ac0b41c3ff5c");
                _containerInfo = new RepoItemInfo(this, "Container", ".//div[#'container']", ".//div[#'container']", 30000, null, "ea6a7cc3-a3ff-4a61-86d3-6169b56f5be0");
                _somepathtagInfo = new RepoItemInfo(this, "SomePathTag", ".//div[#'address-popup-container']/div/div[1]/?/?/a//path", ".//div[#'address-popup-container']//path", 30000, null, "be7f7507-dd62-439b-af8d-108cd0c2a1ac");
                _someatagInfo = new RepoItemInfo(this, "SomeATag", "body/div/div/div//a", "body/div/div/div/div/aside/div/div/a", 30000, null, "873b33e6-867b-4e22-a5f1-808c8dd22535");
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", ".//div[#'p-layout']/aside/div/button[1]", ".//div[#'p-layout']/aside/div/button[1]", 30000, null, "a9e744ba-12a3-4ddc-84f4-09070506aabc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cff41e5e-1b2e-44e3-98d6-b4bb76bda1da")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cff41e5e-1b2e-44e3-98d6-b4bb76bda1da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Trendyol item.
            /// </summary>
            [RepositoryItem("9e435642-11a5-4827-b48a-354c599cf895")]
            public virtual Ranorex.ImgTag Trendyol
            {
                get
                {
                    return _trendyolInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Trendyol item info.
            /// </summary>
            [RepositoryItemInfo("9e435642-11a5-4827-b48a-354c599cf895")]
            public virtual RepoItemInfo TrendyolInfo
            {
                get
                {
                    return _trendyolInfo;
                }
            }

            /// <summary>
            /// The RegisterEmail item.
            /// </summary>
            [RepositoryItem("2e7b06a3-2314-4385-97d8-27231944fda1")]
            public virtual Ranorex.InputTag RegisterEmail
            {
                get
                {
                    return _registeremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmail item info.
            /// </summary>
            [RepositoryItemInfo("2e7b06a3-2314-4385-97d8-27231944fda1")]
            public virtual RepoItemInfo RegisterEmailInfo
            {
                get
                {
                    return _registeremailInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("aec17f8e-c5c5-4cc2-83af-f3fcf4d27463")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("aec17f8e-c5c5-4cc2-83af-f3fcf4d27463")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item.
            /// </summary>
            [RepositoryItem("7bbc9bb5-9329-4750-bd29-0609e7f4543b")]
            public virtual Ranorex.DivTag ErrorBoxWrapper
            {
                get
                {
                    return _errorboxwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorBoxWrapper item info.
            /// </summary>
            [RepositoryItemInfo("7bbc9bb5-9329-4750-bd29-0609e7f4543b")]
            public virtual RepoItemInfo ErrorBoxWrapperInfo
            {
                get
                {
                    return _errorboxwrapperInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("83cbc7dd-b14e-4e31-883a-ac4c791bba2f")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("83cbc7dd-b14e-4e31-883a-ac4c791bba2f")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("eeb68997-f978-449d-ae10-779ff99b63c8")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("eeb68997-f978-449d-ae10-779ff99b63c8")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("b3991852-ece6-43a6-b103-ca27254232bd")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("b3991852-ece6-43a6-b103-ca27254232bd")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The GoToBasketButtonVisible item.
            /// </summary>
            [RepositoryItem("13656bd6-316a-43c4-845c-fcb07027980b")]
            public virtual Ranorex.DivTag GoToBasketButtonVisible
            {
                get
                {
                    return _gotobasketbuttonvisibleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GoToBasketButtonVisible item info.
            /// </summary>
            [RepositoryItemInfo("13656bd6-316a-43c4-845c-fcb07027980b")]
            public virtual RepoItemInfo GoToBasketButtonVisibleInfo
            {
                get
                {
                    return _gotobasketbuttonvisibleInfo;
                }
            }

            /// <summary>
            /// The Sepetim28UEruen item.
            /// </summary>
            [RepositoryItem("1352cbf0-08fc-4a45-b403-701243333497")]
            public virtual Ranorex.DivTag Sepetim28UEruen
            {
                get
                {
                    return _sepetim28ueruenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim28UEruen item info.
            /// </summary>
            [RepositoryItemInfo("1352cbf0-08fc-4a45-b403-701243333497")]
            public virtual RepoItemInfo Sepetim28UEruenInfo
            {
                get
                {
                    return _sepetim28ueruenInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item.
            /// </summary>
            [RepositoryItem("824c4764-73f1-4f0f-bcaf-a1aa5628112c")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize200200
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item info.
            /// </summary>
            [RepositoryItemInfo("824c4764-73f1-4f0f-bcaf-a1aa5628112c")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize200200Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info;
                }
            }

            /// <summary>
            /// The PrdctCntnrWrppr item.
            /// </summary>
            [RepositoryItem("2a233f7a-e2cd-4bdb-8a40-9fe00005b988")]
            public virtual Ranorex.Unknown PrdctCntnrWrppr
            {
                get
                {
                    return _prdctcntnrwrpprInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The PrdctCntnrWrppr item info.
            /// </summary>
            [RepositoryItemInfo("2a233f7a-e2cd-4bdb-8a40-9fe00005b988")]
            public virtual RepoItemInfo PrdctCntnrWrpprInfo
            {
                get
                {
                    return _prdctcntnrwrpprInfo;
                }
            }

            /// <summary>
            /// The AddToBasketButton item.
            /// </summary>
            [RepositoryItem("0ae305a8-494d-411b-bee9-1dad66dde891")]
            public virtual Ranorex.ButtonTag AddToBasketButton
            {
                get
                {
                    return _addtobasketbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasketButton item info.
            /// </summary>
            [RepositoryItemInfo("0ae305a8-494d-411b-bee9-1dad66dde891")]
            public virtual RepoItemInfo AddToBasketButtonInfo
            {
                get
                {
                    return _addtobasketbuttonInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("53ee6a1a-10b7-4e47-8c5a-a0a6eb8eba61")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("53ee6a1a-10b7-4e47-8c5a-a0a6eb8eba61")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The StickyHeader item.
            /// </summary>
            [RepositoryItem("e5736982-173b-4782-8011-c3ce8ed58609")]
            public virtual Ranorex.DivTag StickyHeader
            {
                get
                {
                    return _stickyheaderInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The StickyHeader item info.
            /// </summary>
            [RepositoryItemInfo("e5736982-173b-4782-8011-c3ce8ed58609")]
            public virtual RepoItemInfo StickyHeaderInfo
            {
                get
                {
                    return _stickyheaderInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("a61cca7c-23bd-42f0-b01b-f44678dfa60a")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("a61cca7c-23bd-42f0-b01b-f44678dfa60a")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The Sepetim31UEruen item.
            /// </summary>
            [RepositoryItem("fb1b7390-854a-444f-8d87-a89a5d7c51b2")]
            public virtual Ranorex.DivTag Sepetim31UEruen
            {
                get
                {
                    return _sepetim31ueruenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim31UEruen item info.
            /// </summary>
            [RepositoryItemInfo("fb1b7390-854a-444f-8d87-a89a5d7c51b2")]
            public virtual RepoItemInfo Sepetim31UEruenInfo
            {
                get
                {
                    return _sepetim31ueruenInfo;
                }
            }

            /// <summary>
            /// The PbHeaderWrapper item.
            /// </summary>
            [RepositoryItem("012d566b-bde8-4768-aa01-38e429ce3d9b")]
            public virtual Ranorex.DivTag PbHeaderWrapper
            {
                get
                {
                    return _pbheaderwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PbHeaderWrapper item info.
            /// </summary>
            [RepositoryItemInfo("012d566b-bde8-4768-aa01-38e429ce3d9b")]
            public virtual RepoItemInfo PbHeaderWrapperInfo
            {
                get
                {
                    return _pbheaderwrapperInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("47a57b60-2898-4754-b8a2-6942e58f7521")]
            public virtual Ranorex.PTag Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("47a57b60-2898-4754-b8a2-6942e58f7521")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The FavoritesWrapper item.
            /// </summary>
            [RepositoryItem("8b0f61ab-1017-4dfa-b84f-ac0b41c3ff5c")]
            public virtual Ranorex.DivTag FavoritesWrapper
            {
                get
                {
                    return _favoriteswrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FavoritesWrapper item info.
            /// </summary>
            [RepositoryItemInfo("8b0f61ab-1017-4dfa-b84f-ac0b41c3ff5c")]
            public virtual RepoItemInfo FavoritesWrapperInfo
            {
                get
                {
                    return _favoriteswrapperInfo;
                }
            }

            /// <summary>
            /// The Container item.
            /// </summary>
            [RepositoryItem("ea6a7cc3-a3ff-4a61-86d3-6169b56f5be0")]
            public virtual Ranorex.DivTag Container
            {
                get
                {
                    return _containerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Container item info.
            /// </summary>
            [RepositoryItemInfo("ea6a7cc3-a3ff-4a61-86d3-6169b56f5be0")]
            public virtual RepoItemInfo ContainerInfo
            {
                get
                {
                    return _containerInfo;
                }
            }

            /// <summary>
            /// The SomePathTag item.
            /// </summary>
            [RepositoryItem("be7f7507-dd62-439b-af8d-108cd0c2a1ac")]
            public virtual Ranorex.PathTag SomePathTag
            {
                get
                {
                    return _somepathtagInfo.CreateAdapter<Ranorex.PathTag>(true);
                }
            }

            /// <summary>
            /// The SomePathTag item info.
            /// </summary>
            [RepositoryItemInfo("be7f7507-dd62-439b-af8d-108cd0c2a1ac")]
            public virtual RepoItemInfo SomePathTagInfo
            {
                get
                {
                    return _somepathtagInfo;
                }
            }

            /// <summary>
            /// The SomeATag item.
            /// </summary>
            [RepositoryItem("873b33e6-867b-4e22-a5f1-808c8dd22535")]
            public virtual Ranorex.ATag SomeATag
            {
                get
                {
                    return _someatagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SomeATag item info.
            /// </summary>
            [RepositoryItemInfo("873b33e6-867b-4e22-a5f1-808c8dd22535")]
            public virtual RepoItemInfo SomeATagInfo
            {
                get
                {
                    return _someatagInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("a9e744ba-12a3-4ddc-84f4-09070506aabc")]
            public virtual Ranorex.ButtonTag KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("a9e744ba-12a3-4ddc-84f4-09070506aabc")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The LoginRegister folder.
            /// </summary>
            [RepositoryFolder("11a551ea-c4d6-41f8-8106-896bc281f8a0")]
            public virtual TaskTestRepositoryFolders.LoginRegisterFolder LoginRegister
            {
                get { return _loginregister; }
            }

            /// <summary>
            /// The PrdctCntnrWrppr1 folder.
            /// </summary>
            [RepositoryFolder("e82ef874-1ea4-4089-ac0a-4e7fa3b62647")]
            public virtual TaskTestRepositoryFolders.PrdctCntnrWrppr1Folder PrdctCntnrWrppr1
            {
                get { return _prdctcntnrwrppr1; }
            }
        }

        /// <summary>
        /// The LoginRegisterFolder folder.
        /// </summary>
        [RepositoryFolder("11a551ea-c4d6-41f8-8106-896bc281f8a0")]
        public partial class LoginRegisterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonqbuttonqbuttonmediumqsecondInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _lrcontainerInfo;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _epostaInfo;
            RepoItemInfo _buttonleftmr5qbuttonqbuttonmediuInfo;
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprima1Info;

            /// <summary>
            /// Creates a new LoginRegister  folder.
            /// </summary>
            public LoginRegisterFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginRegister", ".//div[#'login-register']", parentFolder, 30000, null, false, "11a551ea-c4d6-41f8-8106-896bc281f8a0", "")
            {
                _buttonqbuttonqbuttonmediumqsecondInfo = new RepoItemInfo(this, "ButtonQButtonQButtonMediumQSecond", "div[2]/div/button[2]", "div[2]/div/button[2]", 30000, null, "7f95571f-27aa-4006-84a8-bf8c07d674f1");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "div[2]/div/button[2]/span[@innertext='Üye Ol']", ".//span[@innertext='Üye Ol']", 30000, null, "fca8b3ee-1aa1-4cd9-be10-d23b36ccf70c");
                _lrcontainerInfo = new RepoItemInfo(this, "LrContainer", "div[3]", "div[3]", 30000, null, "564348bb-f461-4ab5-aca2-b4518c29b0b1");
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", ".//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//form/button", 30000, null, "3035194b-8c07-429b-a49d-3ee16690cfef");
                _epostaInfo = new RepoItemInfo(this, "EPosta", ".//form[@action='https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F']/?/?/label[@innertext='E-Posta']", ".//label[@innertext='E-Posta']", 30000, null, "3872a33c-4a46-4ede-8d15-32c4ad09af72");
                _buttonleftmr5qbuttonqbuttonmediuInfo = new RepoItemInfo(this, "ButtonLeftMr5QButtonQButtonMediu", "div[2]/div/button[1]", "div[2]/div/button[1]", 30000, null, "8446f02b-2654-4751-913b-941ac4235e2a");
                _qbuttonqbuttonmediumqfluidqprima1Info = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima1", ".//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//form/button", 30000, null, "a852e1a1-01db-4153-acac-1fc21c31aba7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("11a551ea-c4d6-41f8-8106-896bc281f8a0")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("11a551ea-c4d6-41f8-8106-896bc281f8a0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item.
            /// </summary>
            [RepositoryItem("7f95571f-27aa-4006-84a8-bf8c07d674f1")]
            public virtual Ranorex.ButtonTag ButtonQButtonQButtonMediumQSecond
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item info.
            /// </summary>
            [RepositoryItemInfo("7f95571f-27aa-4006-84a8-bf8c07d674f1")]
            public virtual RepoItemInfo ButtonQButtonQButtonMediumQSecondInfo
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("fca8b3ee-1aa1-4cd9-be10-d23b36ccf70c")]
            public virtual Ranorex.SpanTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("fca8b3ee-1aa1-4cd9-be10-d23b36ccf70c")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The LrContainer item.
            /// </summary>
            [RepositoryItem("564348bb-f461-4ab5-aca2-b4518c29b0b1")]
            public virtual Ranorex.DivTag LrContainer
            {
                get
                {
                    return _lrcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LrContainer item info.
            /// </summary>
            [RepositoryItemInfo("564348bb-f461-4ab5-aca2-b4518c29b0b1")]
            public virtual RepoItemInfo LrContainerInfo
            {
                get
                {
                    return _lrcontainerInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("3035194b-8c07-429b-a49d-3ee16690cfef")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("3035194b-8c07-429b-a49d-3ee16690cfef")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The EPosta item.
            /// </summary>
            [RepositoryItem("3872a33c-4a46-4ede-8d15-32c4ad09af72")]
            public virtual Ranorex.LabelTag EPosta
            {
                get
                {
                    return _epostaInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The EPosta item info.
            /// </summary>
            [RepositoryItemInfo("3872a33c-4a46-4ede-8d15-32c4ad09af72")]
            public virtual RepoItemInfo EPostaInfo
            {
                get
                {
                    return _epostaInfo;
                }
            }

            /// <summary>
            /// The ButtonLeftMr5QButtonQButtonMediu item.
            /// </summary>
            [RepositoryItem("8446f02b-2654-4751-913b-941ac4235e2a")]
            public virtual Ranorex.ButtonTag ButtonLeftMr5QButtonQButtonMediu
            {
                get
                {
                    return _buttonleftmr5qbuttonqbuttonmediuInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonLeftMr5QButtonQButtonMediu item info.
            /// </summary>
            [RepositoryItemInfo("8446f02b-2654-4751-913b-941ac4235e2a")]
            public virtual RepoItemInfo ButtonLeftMr5QButtonQButtonMediuInfo
            {
                get
                {
                    return _buttonleftmr5qbuttonqbuttonmediuInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima1 item.
            /// </summary>
            [RepositoryItem("a852e1a1-01db-4153-acac-1fc21c31aba7")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima1
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprima1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima1 item info.
            /// </summary>
            [RepositoryItemInfo("a852e1a1-01db-4153-acac-1fc21c31aba7")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrima1Info
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprima1Info;
                }
            }
        }

        /// <summary>
        /// The PrdctCntnrWrppr1Folder folder.
        /// </summary>
        [RepositoryFolder("e82ef874-1ea4-4089-ac0a-4e7fa3b62647")]
        public partial class PrdctCntnrWrppr1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _fvrtbtn1Info;
            RepoItemInfo _fvrtbtn2Info;

            /// <summary>
            /// Creates a new PrdctCntnrWrppr1  folder.
            /// </summary>
            public PrdctCntnrWrppr1Folder(RepoGenBaseFolder parentFolder) :
                    base("PrdctCntnrWrppr1", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div", parentFolder, 30000, null, false, "e82ef874-1ea4-4089-ac0a-4e7fa3b62647", "")
            {
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", "div[1]/?/?/i", "div[1]/div[2]/i", 30000, null, "dd148756-d5c1-44fd-ba6a-21f9bf303b51");
                _fvrtbtn1Info = new RepoItemInfo(this, "FvrtBtn1", "div[3]/?/?/i", "div[3]/div[2]/i", 30000, null, "7bfe83df-05ec-48da-a3b3-1c303c196586");
                _fvrtbtn2Info = new RepoItemInfo(this, "FvrtBtn2", "div[4]/?/?/i", "div[4]/div[2]/i", 30000, null, "3443ebe4-8260-4030-af70-cf6941eaf06d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e82ef874-1ea4-4089-ac0a-4e7fa3b62647")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e82ef874-1ea4-4089-ac0a-4e7fa3b62647")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("dd148756-d5c1-44fd-ba6a-21f9bf303b51")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("dd148756-d5c1-44fd-ba6a-21f9bf303b51")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn1 item.
            /// </summary>
            [RepositoryItem("7bfe83df-05ec-48da-a3b3-1c303c196586")]
            public virtual Ranorex.ITag FvrtBtn1
            {
                get
                {
                    return _fvrtbtn1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("7bfe83df-05ec-48da-a3b3-1c303c196586")]
            public virtual RepoItemInfo FvrtBtn1Info
            {
                get
                {
                    return _fvrtbtn1Info;
                }
            }

            /// <summary>
            /// The FvrtBtn2 item.
            /// </summary>
            [RepositoryItem("3443ebe4-8260-4030-af70-cf6941eaf06d")]
            public virtual Ranorex.ITag FvrtBtn2
            {
                get
                {
                    return _fvrtbtn2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn2 item info.
            /// </summary>
            [RepositoryItemInfo("3443ebe4-8260-4030-af70-cf6941eaf06d")]
            public virtual RepoItemInfo FvrtBtn2Info
            {
                get
                {
                    return _fvrtbtn2Info;
                }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("0d125380-9fc3-44b8-80b0-1937ada36724")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yenisekmeInfo;
            RepoItemInfo _yenisekme1Info;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/form[@title>'En Trend Ürünler Türkiye''nin']", parentFolder, 30000, null, true, "0d125380-9fc3-44b8-80b0-1937ada36724", "")
            {
                _yenisekmeInfo = new RepoItemInfo(this, "YeniSekme", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/?/?/button[@accessiblename='Yeni Sekme']", ".//button[@accessiblename='Yeni Sekme']", 30000, null, "ff7d3c40-a22a-484e-b081-aee880f26535");
                _yenisekme1Info = new RepoItemInfo(this, "YeniSekme1", "container[@accessiblename>'Yeni Sekme - Google Chrome']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']//tabpage[@accessiblename='Yeni Sekme']", ".//tabpage[@accessiblename='Yeni Sekme']", 30000, null, "8eff0c97-6c3d-4f06-92c1-c5f04ac09555");
                _noneInfo = new RepoItemInfo(this, "None", "container[@accessiblename>'microsoft topluluk - Google''da']/container/?/?/container/container", ".//container", 30000, null, "54a48c33-e155-460e-b7b5-63b63534e053");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0d125380-9fc3-44b8-80b0-1937ada36724")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0d125380-9fc3-44b8-80b0-1937ada36724")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YeniSekme item.
            /// </summary>
            [RepositoryItem("ff7d3c40-a22a-484e-b081-aee880f26535")]
            public virtual Ranorex.Button YeniSekme
            {
                get
                {
                    return _yenisekmeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YeniSekme item info.
            /// </summary>
            [RepositoryItemInfo("ff7d3c40-a22a-484e-b081-aee880f26535")]
            public virtual RepoItemInfo YeniSekmeInfo
            {
                get
                {
                    return _yenisekmeInfo;
                }
            }

            /// <summary>
            /// The YeniSekme1 item.
            /// </summary>
            [RepositoryItem("8eff0c97-6c3d-4f06-92c1-c5f04ac09555")]
            public virtual Ranorex.TabPage YeniSekme1
            {
                get
                {
                    return _yenisekme1Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The YeniSekme1 item info.
            /// </summary>
            [RepositoryItemInfo("8eff0c97-6c3d-4f06-92c1-c5f04ac09555")]
            public virtual RepoItemInfo YeniSekme1Info
            {
                get
                {
                    return _yenisekme1Info;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("54a48c33-e155-460e-b7b5-63b63534e053")]
            public virtual Ranorex.Container None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("54a48c33-e155-460e-b7b5-63b63534e053")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The YeniSekmeAppFolder folder.
        /// </summary>
        [RepositoryFolder("96ba9b8d-3ed2-4e78-957d-6c42a797a14f")]
        public partial class YeniSekmeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new YeniSekme  folder.
            /// </summary>
            public YeniSekmeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("YeniSekme", "/dom[@domain='newtab']", parentFolder, 30000, null, false, "96ba9b8d-3ed2-4e78-957d-6c42a797a14f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("96ba9b8d-3ed2-4e78-957d-6c42a797a14f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96ba9b8d-3ed2-4e78-957d-6c42a797a14f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftToplulukGoogledaAraAppFolder folder.
        /// </summary>
        [RepositoryFolder("abde5879-1b94-43b8-920e-2a2e2d28a9e0")]
        public partial class MicrosoftToplulukGoogledaAraAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _microsoftcommunityInfo;

            /// <summary>
            /// Creates a new MicrosoftToplulukGoogledaAra  folder.
            /// </summary>
            public MicrosoftToplulukGoogledaAraAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftToplulukGoogledaAra", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "abde5879-1b94-43b8-920e-2a2e2d28a9e0", "")
            {
                _microsoftcommunityInfo = new RepoItemInfo(this, "MicrosoftCommunity", ".//div[#'rso']/div[1]/div//a[@href>'https://answers.microsoft']/h3[@innertext='Microsoft Community']", ".//div[#'rso']//h3[@innertext='Microsoft Community']", 30000, null, "cea514d9-4ebb-4299-8214-6baac2f4e6a3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("abde5879-1b94-43b8-920e-2a2e2d28a9e0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("abde5879-1b94-43b8-920e-2a2e2d28a9e0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MicrosoftCommunity item.
            /// </summary>
            [RepositoryItem("cea514d9-4ebb-4299-8214-6baac2f4e6a3")]
            public virtual Ranorex.H3Tag MicrosoftCommunity
            {
                get
                {
                    return _microsoftcommunityInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The MicrosoftCommunity item info.
            /// </summary>
            [RepositoryItemInfo("cea514d9-4ebb-4299-8214-6baac2f4e6a3")]
            public virtual RepoItemInfo MicrosoftCommunityInfo
            {
                get
                {
                    return _microsoftcommunityInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftCommunityAppFolder folder.
        /// </summary>
        [RepositoryFolder("7172a158-0707-4484-be5b-48ecd73b2ee3")]
        public partial class MicrosoftCommunityAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _categorylistgridInfo;
            RepoItemInfo _linkhomecategoryoutlookcomimgInfo;
            RepoItemInfo _hesabımkendiliğindenoutlookagecmişbInfo;
            RepoItemInfo _threadquestiontitlestatusiconsInfo;
            RepoItemInfo _threadmessagecontentreplyandmessageInfo;
            RepoItemInfo _merhabamustafa51533adımjenaynızInfo;

            /// <summary>
            /// Creates a new MicrosoftCommunity  folder.
            /// </summary>
            public MicrosoftCommunityAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftCommunity", "/dom[@domain='answers.microsoft.com']", parentFolder, 30000, null, false, "7172a158-0707-4484-be5b-48ecd73b2ee3", "")
            {
                _categorylistgridInfo = new RepoItemInfo(this, "CategoryListGrid", ".//section[#'categoryListGrid']", ".//section[#'categoryListGrid']", 30000, null, "dc04a9ad-afca-4016-8730-6be13e4fc189");
                _linkhomecategoryoutlookcomimgInfo = new RepoItemInfo(this, "LinkHomeCategoryOutlookComImg", ".//img[#'link-home-category-outlook_com-img']", ".//img[#'link-home-category-outlook_com-img']", 30000, null, "6afd9fb5-859a-4fed-afee-1cb87ad9dd7d");
                _hesabımkendiliğindenoutlookagecmişbInfo = new RepoItemInfo(this, "HesabımKendiliğindenOutlookaGecmişB", ".//div[#'threads']/div[1]//a[@innertext='silinen mesajlarım']", ".//div[#'threads']//a[@innertext='silinen mesajlarım']", 30000, null, "75a4b143-81f1-4c02-8e6a-5d7deeff60f9");
                _threadquestiontitlestatusiconsInfo = new RepoItemInfo(this, "ThreadQuestionTitleStatusIcons", ".//h1[#'threadQuestionTitleStatusIcons']", ".//h1[#'threadQuestionTitleStatusIcons']", 30000, null, "c254db28-21ab-4466-8410-68fce1aec0d6");
                _threadmessagecontentreplyandmessageInfo = new RepoItemInfo(this, "ThreadMessageContentReplyAndMessage", ".//div[#'LastReply']/div/div[2]", ".//div[#'LastReply']/div/div[2]", 30000, null, "dd8a79fb-5b1d-4e4c-b30d-84a6e35f522e");
                _merhabamustafa51533adımjenaynızInfo = new RepoItemInfo(this, "MerhabaMustafa51533AdımJenAynıZ", ".//div[#'LastReply']/div/div[2]/?/?/div[@innertext>'Merhaba, mustafa51_533. Adım']", ".//div[#'LastReply']//div[@innertext>'Merhaba, mustafa51_533. Adım']", 30000, null, "c6dc4752-44b5-42dd-bd23-2b30245790a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7172a158-0707-4484-be5b-48ecd73b2ee3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7172a158-0707-4484-be5b-48ecd73b2ee3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CategoryListGrid item.
            /// </summary>
            [RepositoryItem("dc04a9ad-afca-4016-8730-6be13e4fc189")]
            public virtual Ranorex.SectionTag CategoryListGrid
            {
                get
                {
                    return _categorylistgridInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The CategoryListGrid item info.
            /// </summary>
            [RepositoryItemInfo("dc04a9ad-afca-4016-8730-6be13e4fc189")]
            public virtual RepoItemInfo CategoryListGridInfo
            {
                get
                {
                    return _categorylistgridInfo;
                }
            }

            /// <summary>
            /// The LinkHomeCategoryOutlookComImg item.
            /// </summary>
            [RepositoryItem("6afd9fb5-859a-4fed-afee-1cb87ad9dd7d")]
            public virtual Ranorex.ImgTag LinkHomeCategoryOutlookComImg
            {
                get
                {
                    return _linkhomecategoryoutlookcomimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The LinkHomeCategoryOutlookComImg item info.
            /// </summary>
            [RepositoryItemInfo("6afd9fb5-859a-4fed-afee-1cb87ad9dd7d")]
            public virtual RepoItemInfo LinkHomeCategoryOutlookComImgInfo
            {
                get
                {
                    return _linkhomecategoryoutlookcomimgInfo;
                }
            }

            /// <summary>
            /// The HesabımKendiliğindenOutlookaGecmişB item.
            /// </summary>
            [RepositoryItem("75a4b143-81f1-4c02-8e6a-5d7deeff60f9")]
            public virtual Ranorex.ATag HesabımKendiliğindenOutlookaGecmişB
            {
                get
                {
                    return _hesabımkendiliğindenoutlookagecmişbInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HesabımKendiliğindenOutlookaGecmişB item info.
            /// </summary>
            [RepositoryItemInfo("75a4b143-81f1-4c02-8e6a-5d7deeff60f9")]
            public virtual RepoItemInfo HesabımKendiliğindenOutlookaGecmişBInfo
            {
                get
                {
                    return _hesabımkendiliğindenoutlookagecmişbInfo;
                }
            }

            /// <summary>
            /// The ThreadQuestionTitleStatusIcons item.
            /// </summary>
            [RepositoryItem("c254db28-21ab-4466-8410-68fce1aec0d6")]
            public virtual Ranorex.H1Tag ThreadQuestionTitleStatusIcons
            {
                get
                {
                    return _threadquestiontitlestatusiconsInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The ThreadQuestionTitleStatusIcons item info.
            /// </summary>
            [RepositoryItemInfo("c254db28-21ab-4466-8410-68fce1aec0d6")]
            public virtual RepoItemInfo ThreadQuestionTitleStatusIconsInfo
            {
                get
                {
                    return _threadquestiontitlestatusiconsInfo;
                }
            }

            /// <summary>
            /// The ThreadMessageContentReplyAndMessage item.
            /// </summary>
            [RepositoryItem("dd8a79fb-5b1d-4e4c-b30d-84a6e35f522e")]
            public virtual Ranorex.DivTag ThreadMessageContentReplyAndMessage
            {
                get
                {
                    return _threadmessagecontentreplyandmessageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ThreadMessageContentReplyAndMessage item info.
            /// </summary>
            [RepositoryItemInfo("dd8a79fb-5b1d-4e4c-b30d-84a6e35f522e")]
            public virtual RepoItemInfo ThreadMessageContentReplyAndMessageInfo
            {
                get
                {
                    return _threadmessagecontentreplyandmessageInfo;
                }
            }

            /// <summary>
            /// The MerhabaMustafa51533AdımJenAynıZ item.
            /// </summary>
            [RepositoryItem("c6dc4752-44b5-42dd-bd23-2b30245790a2")]
            public virtual Ranorex.DivTag MerhabaMustafa51533AdımJenAynıZ
            {
                get
                {
                    return _merhabamustafa51533adımjenaynızInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MerhabaMustafa51533AdımJenAynıZ item info.
            /// </summary>
            [RepositoryItemInfo("c6dc4752-44b5-42dd-bd23-2b30245790a2")]
            public virtual RepoItemInfo MerhabaMustafa51533AdımJenAynıZInfo
            {
                get
                {
                    return _merhabamustafa51533adımjenaynızInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
